sudo: false 

language: ruby

before_install:
  - gem install bundler -v '< 2'
     
cache:
  # Cache Ruby bundles
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
    - /usr/local/lib/python3.3/dist-packages/pip/

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: "bash -ex .travis-ci.sh"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

matrix:
  fast_finish: true
  include:
    - rvm: 2.6.0
      env: TASK='htmlproofer'
    - rvm: 2.6.0
      env: TASK='htmlproofer-external'
    - language: rust
      cache: cargo
      before_script:
        - cargo install eipv --version=0.0.4
      env: TASK='eip-validator'
    - python: 3.3
      env: TASK='codespell'
      before_script: "sudo pip install urllib3[secure] && sudo pip install codespell"
  allow_failures:
    - rvm: 2.6.0
      env: TASK='htmlproofer-external'

notifications:
  webhooks:
    urls:
      - https://ethlab-183014.appspot.com/merge/
    on_success: always

addons:
  apt:
    packages:
      "libcurl4-openssl-dev" # https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332767999
