# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >-
  Synthetix Improvement Proposals (SIPs) describe standards for the Synthetix
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "https://sips.synthetix.io"
repository: Synthetixio/SIPs
twitter_username: synthetix_io
github_username: synthetixio
header_pages:
  - all-sip.html
  - all-sccp.html
twitter:
  card: summary
  username: synthetix_io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

permalink: /:slug

defaults:
  - scope:
      path: "SIPS"
    values:
      layout: "sip"
  - scope:
      path: "SCCP"
    values:
      layout: "sccp"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - sccp-x.md
  - sip-X.md
