on: [ pull_request_target ]
name: Auto-Merge Bot
jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    if: github.repository == 'ethereum/eips'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: ethereum/EIP-Bot@16ab13b9d6ce0ba7404afc4a75f2da9e3db69dbb # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          CORE_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1"
          ERC_EDITORS: "@lightclient,@axic,@SamWilsn,@Pandapip1"
          NETWORKING_EDITORS: "@lightclient,@axic,@SamWilsn"
          INTERFACE_EDITORS: "@lightclient,@axic,@SamWilsn,@Pandapip1"
          META_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1"
          INFORMATIONAL_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1"
          MAINTAINERS: "@alita-moore,@mryalamanchi"
