on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'
  workflow_dispatch:

name: Auto Stagnant Bot
jobs:
  auto_merge_bot:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Auto Stagnant Bot
    steps:
      - name: Checkout
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f
      - name: Setup Node.js Environment
        uses: actions/setup-node@25b062c917b0c75f8b47d8469aff6c94ffd89abb
        with:
          node-version: '14'
      - name: auto-stagnant-bot
        uses: ethereum/EIP-Bot@b3ac0ba3600aea27157fc68d1e36c08cc5a6db77 # mark-eips-stale
        id: auto-stagnant-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
