on:
  workflow_run:
    workflows:
      - Auto Review Bot Trigger
    types:
      - completed

name: Auto Review Bot
jobs:
  auto-review-bot:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Fetch PR Number
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          name: pr-number
          workflow: auto-review-trigger.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Number
        id: save-pr-number
        run: echo "pr=$(cat pr-number.txt)" >> $GITHUB_OUTPUT

      - name: Auto Review Bot
        id: auto-review-bot
        uses: ethereum/eip-review-bot@3e9905fcb72cf81ae9ed732df429c28b17e155b1
        continue-on-error: true
        with:
          token: ${{ secrets.TOKEN }}
          config: config/eip-editors.yml
          pr_number: ${{ steps.save-pr-number.outputs.pr }}
