on: [ pull_request_target ]
name: Auto-Merge Bot
jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    if: github.event.pull_request.draft == false && github.repository == 'ethereum/eips'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: ethereum/EIP-Bot@e3dbec627f8c7a5bdc33ca19970e5f9c4af9b626 # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          CORE_EDITORS: "@MicahZoltu,@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1"
          ERC_EDITORS: "@lightclient,@axic,@SamWilsn,@Pandapip1"
          NETWORKING_EDITORS: "@MicahZoltu,@lightclient,@axic,@SamWilsn"
          INTERFACE_EDITORS: "@lightclient,@axic,@SamWilsn"
          META_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn"
          INFORMATIONAL_EDITORS: "@lightclient,@axic,@gcolvin,@SamWilsn"
          MAINTAINERS: "@alita-moore,@mryalamanchi"
  enable-auto-merge:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    needs: ["auto_merge_bot"]
    steps:
    - uses: alexwilson/enable-github-automerge-action@1.0.0
      with:
        github-token: ${{ secrets.TOKEN }}
