on: [pull_request_target]
name: Auto-Merge Bot
jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: ethereum/EIP-Bot@db360cbd0741a3810a0ed7f496c058c9f3f4fd0f # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
          MERGE_ENABLED: false
          CORE_EDITORS: "@MicahZoltu,@lightclient,@axic,@gcolvin"
          ERC_EDITORS: "@lightclient,@axic"
          NETWORKING_EDITORS: "@MicahZoltu,@lightclient,@axic"
          INTERFACE_EDITORS: "@lightclient,@axic"
          META_EDITORS: "@lightclient,@axic,@gcolvin"
          INFORMATIONAL_EDITORS: "@lightclient,@axic,@gcolvin"
  enable-auto-merge:
    runs-on: ubuntu-latest
    needs: ["auto_merge_bot"]
    steps:
    - uses: alexwilson/enable-github-automerge-action@1.0.0
      with:
        github-token: ${{ secrets.TOKEN }}
