name: Manual Bot Rerun
on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: "PR number (with the run you'd like to re-run)"
        required: true
      eventType:
        description: "event type (of the run you want to re-run)"
        required: true
        default: "pull_request_target"
      idOfBotWorkflow:
        description: "id of the bot workflow (just leave as default if you don't know)"
        required: true
        default: "6519716"
      
jobs:
  rerun-bot:
    if: github.repository == 'JEAlfonsoP/eips'
    runs-on: ubuntu-latest
    name: Manual Bot Rerun
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: rerun-workflow
        uses: JEAlfonsoP/EIP-Bot@67247c0463b5d4d47279f907aa0ab318294f6b11 # my-commit
        id: rerun-workflow
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
          PULL-NUMBER: ${{github.event.inputs.pullRequestNumber }}
          ID-TO-RERUN: ${{ github.event.inputs.idOfBotWorkflow }}
          EVENT-TYPE: ${{ github.event.inputs.eventType }}
