on: 
  pull_request_review:
    types: [submitted]
name: Rerun Bot
jobs:
  rerun_bot_on_review:
    runs-on: ubuntu-latest
    name: Trigger Bot Rerun workflow_run
    steps:
      - name: Explanation
        run: echo "this bot is used to trigger another workflow using the workflow_run github event; this is necessary because without it forked PRs do not have access to repo secret; normally this is circumvented using the pull_request_target event but because github actions.. a hack is required to allow the same behavior on pull_request_review; this work-around will no longer be necessary if github ever implements a pull_request_review_target or something similar"